version: "3"
services:
    node9:
        build:
            context: .
            dockerfile: docker/Dockerfile-node-9-alpine
        ports:
            - "3009:3009"
        user: "node"
        environment:
            - NODE_ENV=production
            - DBWEBB_PORT=3009
        volumes:
            - ./:/app/
        command: /bin/sh -c "make test"

    node8:
        build:
            context: .
            dockerfile: docker/Dockerfile-node-8-alpine
        ports:
            - "3008:3008"
        user: "node"
        environment:
            - NODE_ENV=production
            - DBWEBB_PORT=3008
        volumes:
            - ./:/app/
        command: /bin/sh -c "make test"

    node6:
        build:
            context: .
            dockerfile: docker/Dockerfile-node-6-alpine
        ports:
            - "3006:3006"
        user: "node"
        environment:
            - NODE_ENV=production
            - DBWEBB_PORT=3006
        volumes:
            - ./:/app/
        command: /bin/sh -c "make test"
